export const keys = [
  'match_id',
  'tournament',
  'team_a',
  'team_b',
  'stage',
  'start_time',
  'status',
  'winner',
  'game_count',
  'link',
  'game_num',
];

export const matches = [
  {
    _id: 'navi-vs-faze-15-10-2023',
    tournament: 'ESL Pro League Season 18',
    team_a: 'Natus Vincere',
    team_b: 'FaZe Clan',
    stage: 'Quarterfinals',
    start_time: '2023-10-15T18:00:00Z',
    status: 'Ended',
    winner: 'FaZe Clan',
    game_count: 3,
    link: 'https://esl.com/matches/navi-faze-1015',
    game_num: {
      rounds: 19,
      map: 'Mirage',
      round1: {
        victory_type: 'bomb_exploded',
        'duration (seconds)': 112,
        winner: 'a',
      },
      round2: {
        victory_type: 'elimination',
        'duration (seconds)': 87,
        winner: 'b',
      },
      final_score: '13-16',
    },
    game2: {
      rounds: 22,
      map: 'Inferno',
      final_score: '16-14',
      mvp: 'karrigan',
    },
    game3: {
      rounds: 16,
      map: 'Ancient',
      final_score: '8-16',
      highlight_round: {
        round: 12,
        player: 'broky',
        kills: 4,
      },
    },
  },
  {
    match_id: 'g2-vs-vitality-22-11-2023',
    tournament: 'BLAST Premier World Final 2023',
    team_a: 'G2 Esports',
    team_b: 'Team Vitality',
    stage: 'Semifinals',
    start_time: '2023-11-22T20:30:00Z',
    status: 'Ended',
    winner: 'Team Vitality',
    game_count: 2,
    link: 'https://blast.tv/matches/g2-vit-1122',
    game1: {
      rounds: 16,
      map: 'Nuke',
      final_score: '6-16',
      notable_stats: {
        ZywOo: {
          kills: 27,
          adr: 132.5,
        },
      },
    },
    game2: {
      rounds: 14,
      map: 'Overpass',
      final_score: '16-12',
      clutch_rounds: 3,
    },
  },
  {
    match_id: 'heroic-vs-spirit-05-12-2023',
    tournament: 'IEM Katowice 2024 Qualifier',
    team_a: 'Heroic',
    team_b: 'Team Spirit',
    stage: 'Group Stage',
    start_time: '2023-12-05T16:15:00Z',
    status: 'Live',
    winner: null,
    game_count: 1,
    link: 'https://iem.gg/katowice/heroic-spirit',
    game1: {
      rounds: 24,
      map: 'Vertigo',
      current_score: '12-12',
      live_stats: {
        donk: {
          kills: 22,
          headshots: 18,
        },
      },
    },
  },
  {
    match_id: 'furia-vs-liquid-10-01-2024',
    tournament: 'PGL Major Copenhagen 2024',
    team_a: 'FURIA Esports',
    team_b: 'Team Liquid',
    stage: 'Opening Match',
    start_time: '2024-01-10T14:00:00Z',
    status: 'Upcoming',
    winner: null,
    game_count: 0,
    link: 'https://pgl.com/majors/copenhagen/furia-liquid',
  },
  {
    match_id: 'astralis-vs-nip-28-09-2023',
    tournament: 'BLAST Premier Fall Groups',
    team_a: 'Astralis',
    team_b: 'Ninjas in Pyjamas',
    stage: 'Decider Match',
    start_time: '2023-09-28T19:45:00Z',
    status: 'Ended',
    winner: 'Astralis',
    game_count: 3,
    link: 'https://blast.tv/fall-groups/astralis-nip',
    game1: {
      rounds: 16,
      map: 'Anubis',
      final_score: '16-10',
      standout_player: {
        name: 'device',
        rating: 1.52,
      },
    },
    game2: {
      rounds: 21,
      map: 'Inferno',
      final_score: '14-16',
      overtime: true,
    },
    game3: {
      rounds: 16,
      map: 'Mirage',
      final_score: '16-8',
      comeback: 'Astralis won 10 rounds in a row',
    },
  },
];
